### ISSUE TITLE
Had to remove -debug flag from Makefile to compile on linux

### ISSUE THREAD

**Issue by prg318** [atsushieno/sf2xrni#5]
`csc  -platform:x86 -r:NAudio.dll -r:NRenoiseTools.dll sf2xrni.cs -debug
Microsoft (R) Visual C# Compiler version 2.0.0.61404
Copyright (C) Microsoft Corporation. All rights reserved.

error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'
make: *** [Makefile:6: sf2xrni.exe] Error 1
`

Removing -debug from the Makefile fixed this issue for me.

**Comment by atsushieno** [comment]
Okay, you're right in 2017 where we have "csc" on Linux too (it used to be Windows-only).

What makes this problematic is that csc -debug emits pdb which is NOT portable. Fortunately there -debug:portable generates Portable PDB and it works on Linux too. Now It is fixed.

Thanks for the report.
