### ISSUE TITLE
Incorrect loop start & end points

### ISSUE THREAD

**Issue by PerdeT** [atsushieno/sf2xrni#6]
With some sf2 files, looping the sample is broken. The intended start point of the loop becomes the _end_ point, and the start of the sample serves as a start point. Here's a sf2 file in which the problem occurs for reference.

[MegaManX.zip](https://github.com/atsushieno/sf2xrni/files/1632179/MegaManX.zip)

(On Windows, compiled from source with nmake of Visual Studio 2017.)

**Comment by atsushieno** [comment]
I haven't built and used this tool for a while, but to my observation maybe this is the fix? https://github.com/zeromus/sf2xrni/commit/757a688  I will take that change if that looks better to me.

**Comment by PerdeT** [comment]
That indeed fixed the issue! Thanks for a quick answer~

**Comment by atsushieno** [comment]
This is fixed in my repo too. Thanks for the report.
